vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    listing:
      uri_prefix: /uploads/listings
      upload_destination: "%kernel.project_dir%/public/uploads/listings"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
